-- Directors Importer: production-safe, rerunnable migration for MySQL/MariaDB.
SET @db=DATABASE();
SET @sql=IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=@db AND table_name='entity_contacts' AND column_name='original_full_name')=0,'ALTER TABLE entity_contacts ADD COLUMN original_full_name VARCHAR(180) NULL AFTER name','SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=@db AND table_name='entity_contacts' AND column_name='director_utr')=0,'ALTER TABLE entity_contacts ADD COLUMN director_utr VARCHAR(32) NULL AFTER phone','SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=@db AND table_name='entity_contacts' AND column_name='address')=0,'ALTER TABLE entity_contacts ADD COLUMN address TEXT NULL AFTER director_utr','SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=@db AND table_name='entity_contacts' AND column_name='id_number')=0,'ALTER TABLE entity_contacts ADD COLUMN id_number VARCHAR(120) NULL AFTER address','SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=@db AND table_name='entity_contacts' AND column_name='ch_verification_number')=0,'ALTER TABLE entity_contacts ADD COLUMN ch_verification_number VARCHAR(120) NULL AFTER id_number','SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=@db AND table_name='entity_contacts' AND column_name='last_director_import_id')=0,'ALTER TABLE entity_contacts ADD COLUMN last_director_import_id BIGINT UNSIGNED NULL AFTER needs_contact_details','SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF((SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema=@db AND table_name='entity_contacts' AND index_name='idx_contact_entity_email')=0,'CREATE INDEX idx_contact_entity_email ON entity_contacts(entity_id,email)','SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
