<div style="min-height:100vh;display:flex;align-items:center;justify-content:center;padding:28px;background:#eef4f1"><div style="width:100%;max-width:440px;background:#fff;border-radius:28px;padding:36px 34px;box-shadow:0 24px 60px -28px rgba(16,54,45,.35)"><img class="tn-auth-logo" src="/assets/images/trinova-accounting-logo.png" alt="TriNova Accounting">
<h1 style="margin:0 0 8px;font-size:24px">Activate your account</h1><p style="color:#61756e;line-height:1.5">Welcome <?= htmlspecialchars($userName) ?>. Verification is required for <?= htmlspecialchars($email) ?>.</p>
<?php if($error): ?><div style="padding:12px 16px;background:#fdecdc;color:#b45e18;border-radius:14px;margin-bottom:16px"><?= htmlspecialchars($error) ?></div><?php endif; ?>
<?php if($success): ?><div style="padding:12px 16px;background:#e2f3ea;color:#287a52;border-radius:14px;margin-bottom:16px"><?= htmlspecialchars($success) ?></div><?php endif; ?>
<?php if(!$verified): ?>
<form action="/activate" method="post"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars(\Application\Core\Session::csrfToken()) ?>"><input type="hidden" name="token" value="<?= htmlspecialchars($token) ?>"><input type="hidden" name="action" value="verify"><label>6-digit verification code</label><input name="code" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6" required style="width:100%;padding:15px;margin:8px 0 18px;border:1.5px solid #dbe7e3;border-radius:14px;font-size:22px;letter-spacing:7px;text-align:center"><button style="width:100%;padding:15px;border:0;border-radius:14px;background:#0d9488;color:#fff;font-weight:700">Verify email</button></form>
<form action="/activate" method="post" style="margin-top:12px"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars(\Application\Core\Session::csrfToken()) ?>"><input type="hidden" name="token" value="<?= htmlspecialchars($token) ?>"><input type="hidden" name="action" value="resend"><button style="width:100%;padding:12px;border:1px solid #dbe7e3;border-radius:14px;background:#fff;color:#0d9488;font-weight:700">Resend code</button></form>
<?php else: ?>
<form action="/activate" method="post"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars(\Application\Core\Session::csrfToken()) ?>"><input type="hidden" name="token" value="<?= htmlspecialchars($token) ?>"><input type="hidden" name="action" value="password"><input type="password" name="password" minlength="8" placeholder="New password" required style="width:100%;padding:14px;margin-bottom:12px;border:1.5px solid #dbe7e3;border-radius:14px"><input type="password" name="password_confirm" minlength="8" placeholder="Confirm password" required style="width:100%;padding:14px;margin-bottom:18px;border:1.5px solid #dbe7e3;border-radius:14px"><button style="width:100%;padding:15px;border:0;border-radius:14px;background:#0d9488;color:#fff;font-weight:700">Create password and activate</button></form>
<?php endif; ?><p style="text-align:center"><a href="/login">Back to sign in</a></p></div></div>
